### ISSUE TITLE
Polymorphed owl dupe glitch (GardenGear vendors, but maybe others?)

### ISSUE THREAD

**Issue by Thy-boi** [goonstation/goonstation#1005]
[BUG]

**Describe the bug**
Polymorph owl can dupe stuff vended from GardenGear with another person (maybe possible with other vendors?)

**To Reproduce**
1. Be a polymorphed owl
2. Get something from gardengear vendor (was tried with potash bottles)
3. See that you are holding a bottle and another one is on the machine
4. Have someone take the bottle
5. Spill the bottle into a tray or surface
6. Drop the bottle
7. Have other person drop the bottle

**Expected behavior**
You now have 2 empty potash bottles on the floor

**Screenshots**

**Additional context**
Also, other person said that when owl was pouring potash onto a surface, the bottle in their hand became empty

**Comment by pali6** [comment]
Note that it isn't actually duping. Just the item "being in two places".

**Comment by pali6** [comment]
Also I'm pretty sure it's not exclusive to owls. I noticed this when I was stealing lollipops from the medbay lollipop bowl as a flockdrone. 😳

**Comment by Thy-boi** [comment]
Huh

**Comment by Tiggersaurus** [comment]
This sounds similar/related to Borg beakers, when using the UI humans use, the beaker gets "duplicated" with a secondary beaker. Should anyone, purposefully or otherwise, take the beaker it becomes permanently (until module reset) attached to their hands. I believe this is due to coding so that borg can't accidently drop it, like they used to with the bucket.
