### ISSUE TITLE
Bike horn "play note" overlays speech text obscuring it partly.

### ISSUE THREAD

**Issue by Tiggersaurus** [goonstation/goonstation#1096]
[BUG]

**Describe the bug**
When using the clown horn, a play note symbol appears, this might be intentional? But it overlays and obscures the speech text.

**To Reproduce**
1. Have clown bike horn
2. Honk
3. Play note appears and overlays text, I think other people can press it too? Again not sure if intentional?

**Expected behavior**
Text speech to be readable.

**Comment by pali6** [comment]
This is a bit of a problematic layering issue. Because let's say if I open a backpack inventory by clickdragging it onto myself I'd expect that to be above the floating chat since it's HUD stuff. But multicontext menus (like gene booth or new instrument keys) are also in the HUD plane and I don't think that code is modular enough for a change of that (and I'm not even sure where I'd put that stuff since it pretty much *is* HUD).
Maybe instrument keys could appear south of your character instead?

**Comment by Carbadox** [comment]
Bike horns no longer use intrument notes so this is no longer the case
