### ISSUE TITLE
Oshan map correctness failure

### ISSUE THREAD

**Issue by frawhst** [goonstation/goonstation#11387]
### Labels

[BUG] [MAPPING]

### Description

Errors detected!
1 runtimes generated: 
[00:00:09] map_correctness.dm,59: Unanchored objects in walls:
The steel floor tile /obj/item/tile/steel on 178, 197, 1 in North East Maintenance

### Steps to reproduce

1. Post PR
2. Red X of death

### Expected Behavior

Checks pass

**Comment by Sord213** [comment]
FIX IT THEN, DEVELOPER

**Comment by Sord213** [comment]
also I think this is a fluke, or something weird with a random room because there's nothing there since it's a random room area and the only random room with steel tiles spawned in aren't near that spot maybe it's not your fault, developer. I'm gonna chalk this up to a certified *shrug moment and give it the tag to see if anyone else runs into it

**Comment by frawhst** [comment]
Do we generate random rooms during map correctness checks? We probably shouldn’t 
Maybe make a test which generates every random room instead idk

**Comment by frawhst** [comment]
Fixed with define that disables random room generation
