### ISSUE TITLE
Latejoin screen in revolution still shows head slots as unavailable

### ISSUE THREAD

**Issue by Ley-bunned** [goonstation/goonstation#1156]
[BUG]

**Describe the bug**
Late join screen still shows the mode is revolution. The CE spot was shown as taken and there was an X in the check box, the CE died before I tried late joining.  The other head spots were shown as taken from the darkened font but they had lost the check box with an X in it.

**To Reproduce**
1. Load character on revs
2. Late join screen is irregular
3. oh its revs

**Expected behavior**
Late join screen should just show all head slots taken with check boxes with little Xs drawn through them.

**Screenshots**

**Additional context**

**Comment by MarkNais** [comment]
Investigating

**Comment by MarkNais** [comment]
Some "evidence" for further head scratching:
![image](https://user-images.githubusercontent.com/9563541/90349168-a82d3680-dfed-11ea-9851-201f588bf73c.png)
The above was taken June 12 2020
Worth noting: the Captain-square was clickable but would open a pop-up saying that the job was no longer available (or something like that).

![image](https://user-images.githubusercontent.com/9563541/90348932-b7f84b00-dfec-11ea-9239-0ae037fab58e.png)
The above was taken August 16 2020 (incase someone modified the code since I last did)

Not sure what's with the inconsistency. Maybe it's head's entering cryo, dyeing, leaving the Z-level....

**Comment by flappybatpal** [comment]
This still occurs. 1 minute into the round I try to latejoin as NTSO and:
![image](https://user-images.githubusercontent.com/70909958/127705806-ea00fd80-b0db-4b5e-ad80-b5569baacf03.png)

I have looked at the code before and it's really not clear why this would happen as it just marks them as filled.
