### ISSUE TITLE
singulo has no scaling whatsoever for items trown into it

### ISSUE THREAD

**Issue by ZWRh3** [goonstation/goonstation#11637]
### Labels

[BUG][MINOR]

### Description

same as title, nothing matter its always 2 gain even if its a stacked item or a pill vs a high tier loaf

### Steps to reproduce

1. get a stacked item
2. throw it into singulo
3. it gets treated as one in terms of power gain

### Expected Behavior

properly accounting for stacks, and probably scaling based on what item it is too

**Comment by NightmareChamillian** [comment]
isn't this intentional?

**Comment by gear-space** [comment]
Looks like this was implemented and tweaked since the original bug report. 

If an object has a material, energy produced scales on (property * multiplier * amount of material in the individual object) for three different properties, then multiplies by the number in the stack at the end. Verified on devtest it goes through that code and increments gain as intended. 
https://github.com/goonstation/goonstation/blob/226b4f6d785e1455fd975f50d37af2a42108a194/code/obj/machinery/singularity.dm#L399-L405

Loaves don't have any special hardcoded values, but they do increment energy more than just the base 2 things get by default. Objects also count reagents inside, so pills are worth more than the base 2. Going to mark this as closed, but please reopen if I've missed something.
