### ISSUE TITLE
[BUG]Apidae Genetics doesn't work at all

### ISSUE THREAD

**Issue by Sartorius7** [goonstation/goonstation#1215]
[BUG]

Description: Apidae Genetics used to make you vomit out honey upon consumption of a certain threshold. It does not operate anymore, and your pancreas just dies.

Reproduction: 
1. Have Apidae Genetics
2. Eat a ton of sugar with the expectation you will vomit sugar
3. Your pancreas dies and so do you
4. Weep as you just wanted to vomit up human honey

**Expected behavior**
Pancreas takes no damage from sugar, human honey vomitted up at a certain threshold.

**Additional Context**
This mutation was really funny and I want it working again.

**Comment by UrsulaMejor** [comment]
The mutation only triggers if you have more than 200 sugar in your system at once. When it triggers, you immediately lose all sugar in your bloodstream and puke out honey.

The reason why you won't take pancreas damage is because you no longer have any sugar in you after you vomit out the honey.

In other words, in order to trigger this, you'll need to consume a massive amount of sugar at once like, say, a pill, or chocolate gateau
