### ISSUE TITLE
Mop doesn't clean up bloody footprints

### ISSUE THREAD

**Issue by RubberRats** [goonstation/goonstation#12597]
### Labels

[BUG] [MAJOR] [GAME OBJECT]

### Description

As title, the mop no longer cleans up bloody tracks by default.

### Steps to reproduce

1. Wet a mop (WITHOUT CLEANER)
2. Attempt to mop up tracked blood
3. Tracks are not cleaned up

### Expected Behavior

I expected the mop to clean up tracks as it had previously

### Additional Information & Screenshots

I double-checked from an older copy of the codebase to confirm if this actually changed or not. I'm assuming that this wasn't an intentional change

**Comment by flappybatpal** [comment]
I've looked into this and it's due to dried blood.
As far as I understand, the mop does reagent reaction using water and for whatever reason dried blood doesn't interact with it.
Clean forensics (which is commented out) would resolve this but then makes the mop identical to the sponge.

I think the correct solution would be for the mop water to reagent react with dried blood

**Comment by RubberRats** [comment]
Alright, finally got back to looking at this. Seems like a side effect of the commit e1fee89. Going to look into a fix later this week.
