### ISSUE TITLE
Revflash conversion is... weird

### ISSUE THREAD

**Issue by TobleroneSwordfish** [goonstation/goonstation#13978]
### Labels

[BUG]

### Description

Converting someone with a revflash results in a series of confusing messages and the noise being played twice.

### Steps to reproduce

1. Be a head rev
2. Flash someone with the special revflash

### Expected Behavior

Probably just one of these messages

### Additional Information & Screenshots

This is from one click:
![image](https://user-images.githubusercontent.com/20713227/236289120-bad9c0f2-623e-4e31-84dc-69dbbe158984.png)

Found while testing #13959 but I don't think it's related?

**Comment by Mister-Moriarty** [comment]
This occurs due to `/obj/item/device/flash/proc/convert()` being called four times in aggregate by revolutionary flashes;

`flash_mob()` is called twice at lines 437 and 438 in `flash.dm`.
`convert()` is called by the `flash_mob()` override on the revolutionary flash subtype on line 447 of `flash.dm`.
`convert()` is called by `flash_mob()` on the parent flash type on line 181 of flash.dm, which itself if called by the revolutionary flash subtype on line 452 of `flash.dm`.

**Comment by TobleroneSwordfish** [comment]
💀
