### ISSUE TITLE
Re-attaching synthlimbs doesn't halt missing limb bleeding.

### ISSUE THREAD

**Issue by Gerhazo** [goonstation/goonstation#143]
**Describe the bug**
When you lose a limb, you begin uncontrollably bleeding despite how much you try to suture/bandage/styptic it (not sure if this is intended behavior, presumably the reason for it is that you're missing a limb and are leaking blood from it, will assume it as intended for purposes of this bug report).
If you try to re-attach a synthlimb, with the special way those work you don't require the stapling process and just put them on. However, you'll continue bleeding afterwards, as if you were still missing a limb (even though you have one).

**To Reproduce**
1. Spawn in with the green arms (synthlimb arms) trait.
2. Remove one of the synth arms through surgery or admin panel. At this point you begin to bleed uncontrollably no matter how much you try to halt it.
3. Use synthlimb on yourself while targeting the missing limb, this attaches the synthlimb.
4. With the limb re-attached, you'll continue uncontrollably bleeding.

**Expected behavior**
Not bleeding anymore after completing step 3).

**Additional context**
I strongly suspect this is due to how synthlimb re-attaching works in that it doesn't require stapling. There might be some logic missing in that functionality that is present in the stapling one to let the game know not to continue causing bleeding.
To further hint at this, stapling a robotic limb instead will cause the bleeding to stop.

**Comment by ZeWaka** [comment]
Mirror of duplicate further explanation:
**Issue:**
When bleeding, you'll randomly get the message "Your bleeding stops!" multiple times, and not have the indicator of bleeding, but your examine text will read it as being there,  as will health analyzers. You create blood splashes on the floor still, but no actual blood loss occurs.

**Steps to reproduce the behavior:**
1. Cut off very syndicate hat arm you paid 90k spacebux for
2. Put it on
3. Use mender on self to heal bleeding
4. "Phantom bleeding" occurs

**Expected behavior**
The styptic clears the bleeding and examine text doesn't show as bleeding.

**Screenshots**
Uploaded this after roundend, so I can only post chat logs.
https://imgur.com/rp3bPDV - Health analyzer scan
https://imgur.com/wS9GyBH - Chat says the bleeding stopped, but the examine text says otherwise


**Additional context**
Urs was auctioning off a mystery item arm for spacebux, and removed my arm, before replacing it with the very syndicate hat. I've also had this "phantom bleeding" happen to me before, but it seems a bit random with what actually causes it.

**Comment by ryebek** [comment]
Further info, just experienced it again. If you spam examine on yourself while it says you're bleeding when this bug occurs, with a styptic patch on you, it'll stop bleeding occasionally and start again.
