### ISSUE TITLE
Unable to replenish Steel tiles made from own Steel sheets as borg

### ISSUE THREAD

**Issue by Tiggersaurus** [goonstation/goonstation#1480]
**Describe the bug**
Unable to replenish tiles in engineering module made from own steel tiles, met with the error - You cannot combine the steel floor tile with the steel floor tile as they contain different materials! They are clearly both steel.

**To Reproduce**
1. Be engineering borg module
2. Use all of your steel tiles
3. Make a stack of tiles using own steel sheets
4. Try to add them
5. See error

**Expected behavior**
To be able to replenish steel tiles with own module

**Additional context**
Unsure if ALL steel tiles are the issue as I haven't been able to access any yet. Will test. Will also test if the steel sheets have the same issue. Likewise for the wires.

**Comment by mordent-goonstation** [comment]
I have an unrelated question: how are you using all of your steel tiles?! You should be starting with 500. That's enough for a square of 22 tiles on each side with some spare.

**Comment by mordent-goonstation** [comment]
On the actual topic:

I think the main issue that's going to block this is that clicking on a steel sheet/tile with one in your hand (as a human) adds the one in your hand to the stack, rather than the other way around. I think it might be sensible to have the opposite interaction be true. Normally you're trying to vacuum up sheets/tiles anyway into one stack, so having to click once to add your sheet/tile to the stack on the ground and then once more to pick it up (then repeat) is somewhat lame. I know you can do the "click-drag" to stack up a bunch, unsure of whether this works with a cyborg (not tested yet), but if the material is an issue then that will still be blocked currently.

Sounds like the check for the same material between the one in your hand and the one on the ground isn't working right, which would need fixing as part of this, then we can look into how cyborgs can actually try to replenish their stacks.

**Comment by Tiggersaurus** [comment]
Thanks! And I got through them all because I was bug testing! :D And borg can't click drag to stack sheets.

**Comment by MetricDuck** [comment]
Closed in #4504
