### ISSUE TITLE
Singularity exists as an invisible entity

### ISSUE THREAD

**Issue by Drago156** [goonstation/goonstation#1573]
[BUG]

**Describe the bug**
Singularities can be invisible as they move around and affect things, often leading to unnecessary deaths and confusion.

**To Reproduce**
1. Start a singularity engine or let a singularity form from the event
2. Observe stuff being destroyed and pulled by seemingly nothing
3. Probably get sucked into invisible singularity and die

**Expected behavior**
Singularity to show full sprite

**Screenshots**
N/A

**Additional context**
I think this bug has been around for a long while as a mostly clientside issue that just happens? But if there is something that can be identified in code as causing this problem and fixed then yay.

**Comment by Gerhazo** [comment]
Probably a BYOND bug that's been happening for a bit occasionally.
Restarting should make the singularity visible in such cases.

If this happens again, please restart and see if the singularity is still invisible in such case, otherwise there's probably not much that can be done. If it does happen and restarting(not just reconnecting) doesn't work, please do adminhelp in case someone happens to be on to check it out at that time and comment here mentioning as such (or making a new issue if this one gets closed).
