### ISSUE TITLE
Clarion lack of pocket Oxygen tanks

### ISSUE THREAD

**Issue by RGBDeadSilent** [goonstation/goonstation#15958]
### Labels

[BUG]

### Description

Clarion has a distinct lack of Oxygen lockers, but many emergency wall supplies, non contain Pocket Oxygen tanks.

### Steps to reproduce

1. Boot up Clarion
2. Scour the map for Pocket Oxygen tanks
3. Find the former Mini oxygen tank instead, which no longer fits in your pocket

### Expected Behavior

There should be more pocket oxygen tanks on Clarion, there isn't enough of them on the map.

### Additional Information & Screenshots

If I'm wrong and my test was just terrible RNG please disregard.

**Comment by MeggalBozale** [comment]
There are 23 emergency wall supply containers on clarion, and 0 wall supplies (but 18 closets) on cog1. There are 0 emergency closets on clarion. It seems the mapper just had a preference for the wall mounted ones.

You are correct, however, that wall closets don't spawn mini-oxygens. I'll submit a PR to make the loot generation the same for both, since functionally it is reasonable to expect them to be used and placed for the same reason.
