### ISSUE TITLE
mediborg can't fill syringe with internal beaker

### ISSUE THREAD

**Issue by prismfingers** [goonstation/goonstation#16189]
### Labels

 [BUG]

### Description

Mediborgs can't fill their syringe using chemicals in the internal beaker.

### Steps to reproduce

1. be cyborg, select medical
2. equip both beakers and syringe
3. put beakers into some combination of chem-dispenser and/or reagent heater..?
4. eject beaker
5. select syringe and attempt to draw from beaker
6. "You cannot directly remove reagents from this object."

### Expected Behavior

let me fill needle with healing juice using internal beaker

**Comment by Retrino** [comment]
this is a repeat of #15992 which was closed but im not sure the issue was actually resolved. this happens when your beaker is in some kind of container, like a chemmaster or dispenser, and is intentional behavior

a verifiable instance of this actually bugging out even after ejection is the plantmaster, for the sake of reproducing the bug to find the issue

**Comment by prismfingers** [comment]
I see there were some factors I didn't consider. I'll see about

**Comment by prismfingers** [comment]
Did not mean to close that.

**Comment by TobleroneSwordfish** [comment]
should be fixed by #16205, the plantmaster shouldn't have anything to do with it since it doesn't apply the atom prop afaik
