### ISSUE TITLE
New message alerts for TGUI chat don't appear in new tab

### ISSUE THREAD

**Issue by FlameArrow57** [goonstation/goonstation#17056]
### Labels

[BUG]

### Description

Title

### Steps to reproduce

1. Add new chat tab with only combat logs enabled
2. Switch back to main tab

### Expected Behavior

For unread message alerts to appear for new tab

### Additional Information & Screenshots

![image](https://github.com/goonstation/goonstation/assets/53062374/6189a0d9-8f03-496e-88fa-c4455735d544)
Would expect the red box with # of unread messages to appear, but it doesn't

**Comment by CheffieGithub** [comment]
The chat is smart. If you see the message on another tab, it won't tell you that you missed it. So if you were on main with everything enabled, no other tabs would display missed message. If you were on the new tab it would display for main or other tabs.
So if you see the message it doesn't display the new message icon. Intentional.
