### ISSUE TITLE
Case where you can't reach full stamina

### ISSUE THREAD

**Issue by FlameArrow57** [goonstation/goonstation#17422]
### Labels

[BUG][MINOR]

### Description

There's a small case where you can't reach max stamina if the remaining stamina you have left is less than your regen rate

### Steps to reproduce

1. Reach 195 stamina as a human
2. Have 10 stamina regen rate
3. Hover over stamina bar at the top right and see it stay at 195 stamina

### Expected Behavior

For stamina to increase to full stamina

**Comment by TealSeer** [comment]
Verified, but this is actually a visual bug in the stamina bar, you still have 200 stamina internally

**Comment by MeggalBozale** [comment]
if(C.stamina_max <= 0 || abs(C.stamina - last_val) * 32 / C.stamina_max <= 1) return //No need to change anything

Since max stamina is 200 and abs(200-195)*32/200 is 160/200 (<1), it does not change the value. It's odd that this decides whether or not to update based off stamina loss rather than whether or not the icon itself is actually going to change? Idk.
