### ISSUE TITLE
Manufacturer UI is VERY heavy on client performance, causes constant freezing

### ISSUE THREAD

**Issue by TobleroneSwordfish** [goonstation/goonstation#19400]
### Labels

[BUG]

### Description

When using the manufacturer UI on live servers with anywhere near high population my entire game freezes for about a second every time I open it and then stutters again every TGUI render tick. Guh.

### Steps to reproduce

1. Use any manufacturer on live servers.

### Expected Behavior

I expected the UI to not freeze my game constantly.

**Comment by codeJester27** [comment]
I've ran into this issue with the reagent extractor before. The solution is to either cache the list server-side (CheMaster does this, it causes object references to not change on the TGUI end which prevents unnecessary re-renders) or optimize the lifecycle of your components on the TGUI end (ReagentInfo components do this with `onComponentShouldUpdate`, they basically compare the actual properties of the container and reagent objects rather than simply comparing object references; this also should prevent unnecessary re-renders just as well if done correctly).

**Comment by TobleroneSwordfish** [comment]
I ping @MeggalBozale with the curse of manufacturer code.

**Comment by MeggalBozale** [comment]
I specifically did try to make manufacturers performant, hm

**Comment by MeggalBozale** [comment]
> I've ran into this issue with the reagent extractor before. The solution is to either cache lists server-side (CheMaster does this, it causes object references to not change on the TGUI end which prevents unnecessary re-renders) or optimize the lifecycle of your components on the TGUI end ([ReagentInfo components](https://github.com/goonstation/goonstation/blob/2b92649c6b505ee5821a9c955c2aaca922270667/tgui/packages/tgui/interfaces/common/ReagentInfo.tsx#L216-L297) do this with `onComponentShouldUpdate`, they basically compare the actual properties of the container and reagent objects rather than simply comparing object references; this also should prevent unnecessary re-renders just as well if done correctly).

I opted to just have the list be server side, this specific list is updated so frequently due to how resource usage works in a manufacturer anyways

**Comment by MyNameIsRomayne** [comment]
Resolved by #19425
