### ISSUE TITLE
Comm array connections/CentComm terminals are currently useless

### ISSUE THREAD

**Issue by Nexusuxen** [goonstation/goonstation#2227]
[BUG]

**Describe the bug**
The Communications Array dish (labeled as PNET_COM_ARRAY) does not respond to commands nor give any form of feedback upon connection.

**To Reproduce**
1. Connect to a comm array via a TermOS console
2. Try to use 'view' or 'download'
3. Nothing happens

**Expected behavior**
Normally, when you connect to a Communications Array dish (the things that shuttles are called from and such), you are able to enter two commands: View, and Download ## (syntax of ## being the ID of whatever document you wanna download). View will let you see what documents are available, and Download, when provided with the valid ID of a document, will download the file to your terminal.

**Screenshots**
![image](https://user-images.githubusercontent.com/28785926/93715005-7b13fc80-fb34-11ea-80a8-5381da227989.png)
![image](https://user-images.githubusercontent.com/28785926/93715012-86672800-fb34-11ea-826e-5705b5512488.png)

**Additional context**

I believe the CentCom terminal is also supposed to start automatically connected to a comm array, but doesn't - it's just a reskinned TermOS console, though I'm not sure if it has a built-in printer or not. 
This is particularly annoying if some joker ran off with the intel report from the start of the round on RP (since it's kinda god-awful at predicting things and should not be taken seriously on goon main)
It also does not respond to packets with the `command` field being any of the above commands.

**Comment by glassofmilk** [comment]
I just tested locally, and this is working correctly. The commands you want are `command=list` and `command=download&message=1`. I tested on Cog1, and the CENTCOM Terminal started out connected to the comm dish as expected.

**Comment by Nexusuxen** [comment]
Interesting, okay. Seems as though the documentation I was relying on wasn't working, and the Atlas CENTCOM Terminal didn't start out connected. Should I just close the issue then?

**Comment by zjdtmkhzt** [comment]
Seeing as both me and glassofmilk seem to have tested this locally, maybe we should check if it works on the server too?
I'm not sure what the centcomm terminal that you are talking about is, all I see is the communications console, but that uses ThinkDOS, doesn't it?
Anyway, if it turns out that it's not broken, we should probably update zamus wiki page, seeing as that is what everyone seems to use. :p

**Comment by Xkeeper0** [comment]
The documentation says that because that's how it *used* to work, back in the day. See this section from the 2016 release:

https://github.com/goonstation/goonstation-2016/blob/565c5e50bc7a7705cb269db33234bd3b87c2564d/code/WorkInProgress/computer3/comm_dish.dm#L219-L272

The `command=list` and `command=download&message=1` format is correct and the (unofficial!) documentation is out of date. Tested in a live round, though you might have to connect to the communications dish manually as not all of them start connected.
