### ISSUE TITLE
Combustion Chamber Spell: Plasma deletus

### ISSUE THREAD

**Issue by Schnugaf** [goonstation/goonstation#2303]
[BUG]

**Describe the bug**
The bug causes the combustion chamber for TEG to instantly vent all gasses and then venting faster than it is  possible to fill for a reasonable burn. It basically makes a burn in the combustion chamber not viable anymore.

**To Reproduce**
1. Get RCD
2. Set RCD to construct floor/wall
3. Construct wall by one of the vent doors in combustion chamber
4. Watch the gas disappear immediately

Replicated on Cog2 while on goonstation. Replicated on cog1 when hosting private server.

**Expected behavior**
I'd expect the gas to vent slower, not faster, when there is more in the way between the injector and space. I'd also expect the gas to act the same when said wall is removed regardless of which type of floor is beneath it.

**Screenshots**

**Additional context**

**Comment by geneva-breaker** [comment]
This is the intended behavior actually. 
Building a wall in the door updates the airgroup, which makes it notice the direct path to space. 

The actual bug is that opening the door itself does not produce the same update. 
This will be corrected eventually, which *should* fix the combustion chamber exploit. 

Hellburning in the chamber is not a feature.
