### ISSUE TITLE
Unsecured assemblies still detonate the assembly.

### ISSUE THREAD

**Issue by DicksonOrmus** [goonstation/goonstation#2440]
[BUG]

Title. 

**To Reproduce**
Create an assembly of any kind.  Pipe bomb or beaker using a remote detonate.
Don't secure it with screw driver so it says "will now work
**Expected behavior**
It's not supposed to detonate unless secured once on the item by a screw driver.

*

**Comment by GarrettStock** [comment]
Unsure if this is the case with timer based pipe bombs, but can confirm that this is the case with remote signalers. Fairly certain that this is the same with proximity detectors as well.

When you attach an assembly to a pipe bomb, in theory, you then secure the assembly with a screwdriver.
The chat log will then prompt you with a chat message saying "the assembly is now secure and the igniter will now work." or something along those lines.

Can confirm that i was carrying 6 pipe bombs with a default radio signal on it, and assumed it was fine because the assemblies were not secure. They all then detonated in spite of being unsecured.

**Comment by GarrettStock** [comment]
Unsure if this is the case with timer based pipe bombs, but can confirm that this is the case with remote signalers. Fairly certain that this is the same with proximity detectors as well.

When you attach an assembly to a pipe bomb, in theory, you then secure the assembly with a screwdriver.
The chat log will then prompt you with a chat message saying "the assembly is now secure and the igniter will now work." or something along those lines.

Can confirm that i was carrying 6 pipe bombs with a default radio signal on it, and assumed it was fine because the assemblies were not secure. They all then detonated in spite of being unsecured.
