### ISSUE TITLE
Progress Bars getting stuck above character and action never finishing

### ISSUE THREAD

**Issue by Luxizzle** [goonstation/goonstation#2444]
[BUG]

**Describe the bug**
Tried to get over a railing, the progress bar finished but i never got over the railing, tried again, no difference. Restarted my client to see if that was the problem, but rejoined with a stuck progress bar over my head, tried again, no difference. Tried to use a screwdriver on the railing so i could move it, also had a progress bar, but also got stuck.

After walking around the station, multiple people were having this problem, so its a server-wide thing.

**To Reproduce**
1. ???
2. Try to get over railing
3. Progress bar gets stuck
4. All following actions with a progress bar also get stuck

**Expected behavior**
The progress bar not getting stuck and being able to finish the action.

**Screenshots**

![image](https://user-images.githubusercontent.com/14966486/96330301-761f6b80-1054-11eb-84af-acda60b3e30d.png)

![image](https://user-images.githubusercontent.com/14966486/96330423-491f8880-1055-11eb-9385-9b48acc3f326.png)

**Comment by ThePotato97** [comment]
This sounds more like it was linked to something else that happened on the server rather than a progress bar bug.

**Comment by Tarmunora** [comment]
action process probably hung - worth keeping an eye out for actionbar-related runtimes

**Comment by Gerhazo** [comment]
To elaborate on what was already mentioned,
Optimal course of action in cases like these is to adminhelp and hopefully someone who's available will fix the issue if necessary as well as have the tools to look into potential causes.
If there's one specific action you or anyone else for the matter has identified that seems to reliably reproduce this that's definitely worth reporting. The bar being stuck after performing an action such as the forementioned railing jump is a symptom of an issue causing these to be stuck, rather than a cause.

**Comment by pali6** [comment]
Not really a useful report in the current form as we have no idea what could have hung the process in that particular round. Closing.
