### ISSUE TITLE
RE: codelock/safelock change

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#246]
I'm posting this here to express some difficulties some people have had adjusting to how the code lock/safe cracking has changed from what it was previously.

(I know there is another method of solving the new way than whats used in the example, and Ive had it explained to me, but at the time of writing this there was a conversion about the changes in the discord and I'm mostly posting this here to archive thoughts/concerns/issues, some people have had. Additionally, posting this here to facilitate more discussion)

Issue is. now is grumpy beep means something different now, it used to mean that the number was in the first slot. now it means its in the right slot.
it would boop if the number WASNT in the first slot. meaning that number was in the code. so a grumpy beep would bee the first slot and the any boops from other numbers would be the other numbers in the code that would change to beeps when in the right slot.

when this fixed happened this changed. now grumpy beep is right number in right place. and boop is right number wrong place. loosing knowing the first slot DEFINITIVELY makes code lock/safe cracking significantly slower/harder than it once was.

even if this is closer to than intended method. it makes it feel more time consuming than it really should be

(for this example 7 is in the correct position, the first slot, all the other number are in the code, but wont be told as that irrelevant to the example)

7A14
7A41
74A1
741A
71A4
714A

with the previous way it worked, knowing the first slot DEFINITIVELY would mean one of these is the correct, meaning these would be the only ones i had to brute force. with the podlock/safe code fix i would now have to do those along with

14A7
147A
17A4
174A
1A47
1A74
A741
A714
A174
A147
A471
A417
4A17
4A71
47A1
471A
41A7
417A

Brute forcing this way FEELS significantly more time consuming. additionally i often forget which ones i have already input, so i often do some more than once.

the big issue is that that it code breaking feels slower than it once was.
additionally. making queries in game versus IRL is slower do to how the codelock/safes are rather slow input.

(originally posted on a closed PR, but posting here to help facilitate discussion as closed PRs can get buried )

(also its kinda strange i can only label an issue as an bug, but thats just my thinking)

**Comment by Adharainspace** [comment]
how most people did safes was brute forcing the nums, which would take 4 guesses. (its a number that doesnt change based on method so we will just use the same number for both examples)
so youd go through every number on the numpad like
1111
2222
3333
4444 
and so on
until you got confirmation on which numbers were in there through beeps and boops
since the beep meant that that number was in the first slot
(say, in this example, that 1 beeped, and 2,3,4 booped)
you would need to do 3! more brute force guesses to figure it out, as opposed to 4!
1234
1243
1324
1342
1423
1432
after that, you would have definitely found the combination, and the amount of entries it took was 4 to find the numbers and 6 to find the correct sequence, for a total of **10** inputs

for bruteforcing how things are currently, you would do
1111
2222
3333
4444
until you find all 4 numbers that make a sound
then, in order to find which comes first, you need to use a number that isnt a part of the passcode, so any number thats not the 4 you just found (in this example, 5)
1555
2555
3555
at that point youve either gotten a hit for 1,2 or 3 being the first number, or you havent, in which case the first number is the one you havent tested yet.
then its back to brute forcing like before (lets say the first number was in fact 4)
4123
4132
4213
4231
4312
4321
at that point you would have definitely found the number, and it wouldve taken 4 inputs to find the numbers, 3 inputs to find the first, and 6 to find the total sequence for a total of **13** inputs

however, bc the new way its coded leaves u with more info, theres another way u can do stuff, i cant paste it here yet tho, gimmie a little while to do school stuff

**Comment by Adharainspace** [comment]
okay and the 3rd way, maybe not mathetmatically perfect is as follows
brute force as usual to get the 4 numbers
1111
2222
3333
4444 etc
then, use the garbage number (0) plus your identified numbers to figure out which the first number is
1000
2000
3000
so in this case either (1,2,3) were the first number, or because none of them were, 4 has to be the 1st number
we will say the first number is 1, for ease of reading. then to figure out the 2nd number, you do
1200
1300
after those two inputs, you know that the 2nd number was either 2 or 3, or if it was neither then it was four. lets say the 2nd number was 2
1230
after this final input, you will know that either:
3 is the 3rd number, so 4 must be the 4th number
OR
3 is not the 3rd number, so 4 must be the 3rd number and 3 must be the 4th number
after this you will know what the password is with certainty
so the total amount of inputs was 4 to get the numbers, plus 6 to figure out the sequence they go in
 for **10** total inputs.

**Comment by Adharainspace** [comment]
even though the old way of bruteforcing and the new way of using the beeps to validate numbers have the same amt of theoretical inputs, the 2nd way probably takes a bit  more time bc you have to think a little more

**Comment by MarkNais** [comment]
I've been following the above method since I've learned safe cracking, and I can't say I mind the latest update.
