### ISSUE TITLE
spacemas fruitcake recipe broken

### ISSUE THREAD

**Issue by Matticus0** [goonstation/goonstation#2901]
[BUG]

**Describe the bug**
When adding ???? produced by the oven and The Very Concept of Fried Food produced by the deep fryer to the oven as described on the wiki (High, 7) only ???? is produced.

**To Reproduce**
1. Make ???? using random non-food object in oven
2. Make The Very Concept of Fried Food using random object in fryer
3. Cook both at High, 7 in oven as per wiki
4. No fruitcake

**Expected behavior**
Fruitcake make

Perhaps something to do with fryer changes since last Christmas?

**Comment by NoahButtes** [comment]
After doing some code diving, this appears to be happening because the fruit cake recipe requires /obj/item/reagent_containers/food/snacks/yuckburn (otherwise known as a Smoldering Mess) as one of the ingredients:

https://github.com/goonstation/goonstation/blob/0e462bd4c29e7df285cc1f70197ffec309063dd8/code/datums/cookingrecipes.dm#L1183-L1185

The Physical Manifestation of the Very Concept of Fried Food does, in fact, contain a Smoldering Mess, but it's held within a fryholder item. 

https://github.com/goonstation/goonstation/blob/dc3b017e7c93a7a3cda5437e4b815621e3f7dfee/code/obj/machinery/deep_fryer.dm#L177-L197

The oven only sees the crispy golden shell rather than the smoldering mess inside that shell. This is why the fruit cake recipe breaks.

**Comment by zjdtmkhzt** [comment]
Welcome to the first anniversary of this issue! It is indeed still and issue, and I believe it is as Camryn says.

**Comment by zjdtmkhzt** [comment]
Right, I checked again, and when using the actual needed items, (a smoldering mess and a ????) the recipe seems to work properly.
So the problem here was just user error with the wrong recipe, frying is not involved in the creation of this!
