### ISSUE TITLE
Unredeemable Spy thief reward

### ISSUE THREAD

**Issue by SirSnek** [goonstation/goonstation#3023]
[BUG]

**Describe the bug**
The NT Poster is not redeemable in any way or atleast it seems like it. Click dragging the pda onto it doesn't do anything, click dragging it onto the pda does not do anything either. Wire cutters do nothing to get it down thus it's unredeemable

**To Reproduce**
1. Become a spy thief
2. Get NT poster as one of the items you need to steal
3. Try redeeming it
4. Nothing happens
**Expected behavior**
Either A: Let players cut it off the wall with cutters and redeem it that way or B: Make it so Click dragging it onto your pda works just like with any other non handheld item

**Screenshots**

**Additional context**
I was a spy thief on oshan and had to steal that specific poster, i tried out 2 diffrent NT posters, the one  by cargo and one near the bridge. I haven't gotten any other posters as targets so they may be problematic too.

**Comment by virvatuli-gh** [comment]
Hey there! I was the mentor trying to help you figure this out when it was going on. I think I figured out what the issue was but I just need you to confirm something for me, which of these two posters did you try to claim? They both have the _same name_ but only one is a spy bounty. I'm guessing you tried to claim the blue one?

![2020-12-16 18_36_47-Goonstation Development_ Deep Space Object Gamma](https://user-images.githubusercontent.com/68257280/102419731-5feb4880-3fce-11eb-9581-31f2adbab937.png)

**Comment by SirSnek** [comment]
Yes I did try claiming the blue one. and after the fact i did see that they
were named the same thing. But at that point the bounty changed so i
couldn't test it. To avoid confusion it should probably be renamed to
something like "NT recruitment poster"

czw., 17 gru 2020 o 00:42 virvatuli-gh <notifications@github.com>
napisał(a):

**Comment by virvatuli-gh** [comment]
> Yes I did try claiming the blue one. and after the fact i did see that they were named the same thing. But at that point the bounty changed so i couldn't test it. To avoid confusion it should probably be renamed to something like "NT recruitment poster"

Thanks for letting me know! That's exactly what I had planned.
