### ISSUE TITLE
Cant write on papers on clipboard

### ISSUE THREAD

**Issue by Oaklizard-2047** [goonstation/goonstation#3025]
[BUG]

**Describe the bug**
When holding a clipboard and opening it, there isnt an option to write on the papers put into it.

**To Reproduce**
1. Grab a clipboard
2. Put a paper in it
3. Use the clipboard and see there's no "write" option

**Expected behavior**
There should be a write option, considering the previous version has one

**Additional context**
This bug happened after the writing update

**Comment by BatElite** [comment]
Since TGUI paper, writing and reading happens in the same window - holding a pen while reading the paper should work.
However, there was an issue in that the TGUI code wasn't checking for the pen on the clipboard itself, which might have contributed to the issue? (and which is what my bugfix actually addresses.)

**Comment by Oaklizard-2047** [comment]
yes that method works, which seems intentional for realism. So is the removal of the write option on the clipboard intentional or not?

**Comment by Oaklizard-2047** [comment]
That might be the issue, as before TGUI, a pen is needed on the clipboard in order for the write option becomes available.
