### ISSUE TITLE
Matter eating your arms and legs doesnt delete them properly and runtimes when trying to interact with anything in the enviroment

### ISSUE THREAD

**Issue by Carbadox** [goonstation/goonstation#3353]
[BUG]

**Describe the bug**
Using matter eater on yourself to eat your limbs doesnt delete them properly. You can also eat your own ass and still fart. They're not gone in the description text, they're still present on the sprite and the inhand icons are still there. However trying to click anywhere runtimes in human.dm, line 2806
Eyes are not affected 

**To Reproduce**
1. Give yourself matter eater (set cooldown to 0 to make things easier)
2. Eat your limbs
3. Observe yourself

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Carbadox** [comment]
Might be related to your mutant race changes @Superlagg?

**Comment by Superlagg** [comment]
> Might be related to your mutant race changes @Superlagg?

Doesnt look like anything I did.

human.dm:2806 might be something with this:
`		if (limbs) //Wire: fix for null.r_arm and null.l_arm
			arm = hand ? limbs.l_arm : limbs.r_arm // I'm so sorry I couldent kill all this shitcode at once
		if (arm)
			arm.limb_data.attack_hand(target, src, can_reach(src, target), params, location, control)
`

arm gets set even if there are no arms, since limbs is always set.

Matter eater qdels the affected thing. Looking at disposing() in mob_parts, looks like it tries to remove the limb from the owner's organHolder... which doesnt hold limbs. So its probably not telling the mob's limbs datum that the limb is gone. It also deletes the limb's limb_data_ which human.dm:2806 tries to reference, but fails due to it not existing on a limb that also doesn't exist.

Farting uses get_organ, which references the mob's organHolder's organ list, which isn't updated when a butt is qdeled. The list likely still has a valid type in there, which emote.dm might be interpreting as a valid butt. As for why it doesn't runtime, emote.dm doesn't try to reference the butt's vars directly, and falls back to default fart behavior if all the special butt checks fail. Neat!

Normal organs don't seem to be affected as their disposal correctly removes themselves from the proper vars.

**Comment by MetricDuck** [comment]
Closed with #8606
