### ISSUE TITLE
Flamethrowers not delivering chems

### ISSUE THREAD

**Issue by Sartorius7** [goonstation/goonstation#3556]
[BUG]

**Describe the bug**
Flamethrowers deliver no chems

**To Reproduce**
1. Fill a flamethrower with a reagent
2. Spray target with reagent
3. No chems are inside the target
4. Weep

**Expected behavior**
Chemicals absorbed by target ala classic flamethrower behavior to allow for fun things like booze flamethrowers that intoxicate targets

**Comment by Carbadox** [comment]
I've had the same issue, synthflesh seems to only work only once it passes 5 tiles, then the gibs start to spread

**Comment by Tarmunora** [comment]
> Flamethrowers deliver no chems
Not a bug - removal of that functionality was intentional with the intent of keeping consistency with other chemical application methods. Touch reactions, and any potential skin penetration from valid chems, will apply in a similar vein to similar methods (beaker splash, aerosol, etc)

> I've had the same issue, synthflesh seems to only work only once it passes 5 tiles, then the gibs start to spread
You may need to turn up the chamber volume on the flamethrower, and keep it to semi-auto, in order to have a sufficient volume/turf to create the messes
