### ISSUE TITLE
Zipgun can't fire after being loaded from LMG Belt

### ISSUE THREAD

**Issue by flappybatpal** [goonstation/goonstation#3637]
[BUG - MINOR]

**Describe the bug**
If a zip gun has been loaded from a nukie LMG belt it will show 2 ammo but not fire with a *click click*.

**To Reproduce**
1. Acquire a zip gun
2. Acquire a /obj/item/ammo/bullets/lmg 
3. Load the zip gun from the belt
4. Try to fire the gun

**Expected behavior**
Zipgun would fire bullets as usual

**Additional context**
May apply to other ammo.

Failing to fire due to  (!canshoot()) on line:
https://github.com/goonstation/goonstation/blob/66ad7af6a49b3d25b12f3521dfb302f41bc2bd0c/code/obj/item/gun/gun_parent.dm#L362

**Comment by Superlagg** [comment]
Its because burstfire is defined by the ammo and not (usually) the gun. The way burstfire works is that the projectile first checks if there's enough ammo for a complete burst, then fires itself that many times. Its a lot like an energy weapon, treating the burst as a single projectile that costs a certain amount of ammo to fire. LMG projectiles cost about 8 ammo to fire, which since zipguns only hold 2 shots, it thinks it doesnt have enough ammo.

**Comment by flappybatpal** [comment]
Guessing that your mega PR will probably change all this and it might be pointless to fix a real edge case at the moment?

https://github.com/goonstation/goonstation/pull/2752

**Comment by Superlagg** [comment]
> Guessing that your mega PR will probably change all this and it might be pointless to fix a real edge case at the moment?
> 
> #2752

Hah, nah, that PR has like no chance to ever be merged like it is. Also it can be fixed by just putting a return after the qdel, a one line fix.
