### ISSUE TITLE
TermOS computers do not "see" the entire network after a powernet cable-fix.

### ISSUE THREAD

**Issue by MarkNais** [goonstation/goonstation#366]
[MINOR]

**Describe the bug**
TermOS (and maybe ThinkDOS?) computers do not see the entire network after fixing broken cables.

**To Reproduce**
Okay, I tested this on Atlas, here's the setup. There's a roundstart termOS computer in AI foyer and I'm labeling that AI-term. Everything else takes place in the mechanics room with it's 4 spare data terminals.
1.	Cut the powernet so that you have a small network (say, a network of only the mechanics room).
2.	Attach a packet sniffer to the small network.
3.	Make a termOS computer, call it MY-term
4.	On MY-term, run term_ping, and see few or no responses
5.	On AI-term, run term_ping, and see an appropriate number of responses.
6.	Observe the packet sniffer, should only see traffic on the small network. Good so far.
7.	Fix the powernet.
8.	On MY-term, run term_ping, and see few or no responses
9.	Observe the packet sniffer, should only see traffic as though the network was still small!
10.	On AI-term, run term_ping, and see an appropriate number of responses.
11.	Observe the packet sniffer, it shows traffic for the large network!
12.	Running term_ping on MY-term still shows a reduced network.

**Expected behavior**
After rebuilding the powernet, the termOS computer should see the entire network.

**Additional context**
Note: completely dismantling and rebuilding the computer did not fix the issue.

**Comment by MarkNais** [comment]
Upon further testing: MY-term can see the whole network if you remove and replace the cable "connected" to the data-terminal.

**Comment by flrsh** [comment]
Powernets are not properly being assigned to data terminals when cables are joined. Data terminals can receive signals because they've been added back to the "main" powernet, but they can't send them because their assigned powernet is still the old one. 

Removing and replacing a connected cable has the potential to fix this. Depending on the directions of the cable that was cut (lol), the "main" powernet will be recreated (see `/datum/powernet/proc/cut_cable(var/obj/cable/C)` of `power_parent.dm`) and properly assigned to their data terminals.
