### ISSUE TITLE
Manta brig phone is sideways!

### ISSUE THREAD

**Issue by DimWhat** [goonstation/goonstation#3741]
[BUG]

**Describe the bug**
The wall phone in manta's brig is sideways and does not have the correct sprite.

**To Reproduce**
1. Go to manta security.
2. Go look at the wall phone in manta's brig.
3. See bug.

**Expected behavior**
The sprite to be the normal sideways sprite.
**Screenshots**
![image](https://user-images.githubusercontent.com/40079883/108004161-a0f5de00-6fba-11eb-8b0a-31979ba1f628.png)

**Additional context**
I saw this on an RP round.

**Comment by nefarious6th** [comment]
Wasn't able to reproduce this one. Checked the icon variables and they're all fine; something happened here with the icon loading since the phone in the screenshot is the normal landline and not the wall-mounted which it's defined as being. Running locally shows the wall-mounted with the red overlay.

**Comment by Carbadox** [comment]
Can confirm, could not reproduce
