### ISSUE TITLE
Items don't stop animating spin after being thrown

### ISSUE THREAD

**Issue by ZeWaka** [goonstation/goonstation#389]
[MINOR]

**Describe the bug**
Looks like the animation is not getting cleared when items stop being thrown.

**To Reproduce**
1. blow up a human
2. stuff doesn't stop animation

**Expected behavior**
stop animating

**Screenshots**
![2020-04-22_17-13-56](https://user-images.githubusercontent.com/4741640/80045613-d3c76680-84bc-11ea-9bb8-d29866368fec.gif)

**Comment by IHadMyUsernameTaken** [comment]
I managed to get a similar issue by just lining up two carbons with baseball bats (spawning two assistants and giving them baseball bats seemed fairly easy, but item limb bats work too) to look at each other and throwing some item at one of them to have them bat it back and forth for some time (this batting might happen too fast for you to even see anything in particular, and any sounds and messages aren't even shown due to the way how batting works right now) until the item stops on either of the carbon's tile rotating and the following runtime error is produced:

Maximum recursion level reached (perhaps there is an infinite loop) To avoid this safety check, set world.loop_checks=0.

``
proc name: CanPass (/turf/simulated/floor/CanPass)
  usr: Marion Agg (/mob/living/carbon/human)
  src: the steel floor (190,108,1) (/turf/simulated/floor)
  usr.loc: the steel floor (194,109,1) (/turf/simulated/floor/yellow/side)
  call stack:
the steel floor (190,108,1) (/turf/simulated/floor): CanPass(the electrical toolbox (/obj/item/storage/toolbox/electrical/mechanic_spawn), the steel floor (190,108,1) (/turf/simulated/floor), null, null)
the steel floor (190,108,1) (/turf/simulated/floor): Enter(the electrical toolbox (/obj/item/storage/toolbox/electrical/mechanic_spawn), the steel floor (189,108,1) (/turf/simulated/floor))
the electrical toolbox (/obj/item/storage/toolbox/electrical/mechanic_spawn): Move(the steel floor (190,108,1) (/turf/simulated/floor), null)
the electrical toolbox (/obj/item/storage/toolbox/electrical/mechanic_spawn): Move(the steel floor (190,108,1) (/turf/simulated/floor))
the electrical toolbox (/obj/item/storage/toolbox/electrical/mechanic_spawn): throw at(space (299,108,1) (/turf/space), 50, 25, null, null, 1)
the electrical toolbox (/obj/item/storage/toolbox/electrical/mechanic_spawn): throw impact(Davis Langston (/mob/living/carbon/human/normal/assistant), null)
the electrical toolbox (/obj/item/storage/toolbox/electrical/mechanic_spawn): hit check()
the electrical toolbox (/obj/item/storage/toolbox/electrical/mechanic_spawn): throw at(space (1,108,1) (/turf/space), 50, 25, null, null, 1)
the electrical toolbox (/obj/item/storage/toolbox/electrical/mechanic_spawn): throw impact(Rylan Demuth (/mob/living/carbon/human/normal/assistant), null)
the electrical toolbox (/obj/item/storage/toolbox/electrical/mechanic_spawn): hit check()
...
the electrical toolbox (/obj/item/storage/toolbox/electrical/mechanic_spawn): hit check()
the electrical toolbox (/obj/item/storage/toolbox/electrical/mechanic_spawn): throw impact(Davis Langston (/mob/living/carbon/human/normal/assistant), null)
the electrical toolbox (/obj/item/storage/toolbox/electrical/mechanic_spawn): throw at(space (1,108,1) (/turf/space), 50, 25, null, null, 1)
the electrical toolbox (/obj/item/storage/toolbox/electrical/mechanic_spawn): hit check()
the electrical toolbox (/obj/item/storage/toolbox/electrical/mechanic_spawn): throw impact(Davis Langston (/mob/living/carbon/human/normal/assistant), null)
the electrical toolbox (/obj/item/storage/toolbox/electrical/mechanic_spawn): throw at(space (1,108,1) (/turf/space), 50, 25, null, null, 1)
the electrical toolbox (/obj/item/storage/toolbox/electrical/mechanic_spawn): hit check()
Marion Agg (/mob/living/carbon/human): throw item(the wall (194,106,1) (/turf/simulated/wall/auto/supernorn), /list (/list))
Somethings (/client): Click(the wall (194,106,1) (/turf/simulated/wall/auto/supernorn), the wall (194,106,1) (/turf/simulated/wall/auto/supernorn), "mapwindow.map", "icon-x=22;icon-y=5;left=1;scre...")
``

As can be seen in the runtime error's call stack, the batters would appear to be causing enough calls for the maximum recursion level to be achieved with their repeating batting of the item we threw.

**Comment by ZeWaka** [comment]
> As can be seen in the runtime error's call stack, the batters would appear to be causing enough calls for the maximum recursion level to be achieved with their repeating batting of the item we threw.

That is a different issue entirely though, I'm pretty sure this one was just cause by the recent bugs in BYOND's animation system. That bug is due to not rate-limiting baseball bats knockback effect.

**Comment by IHadMyUsernameTaken** [comment]
Fair enough, I wasn't entirely sure where to put this, and this looked like it could be related when I was looking around.

**Comment by ZeWaka** [comment]
BYOND bug. Fixed.
