### ISSUE TITLE
Zombies can't turn NPC monkeys into other zombies via brain eating

### ISSUE THREAD

**Issue by Enakai** [goonstation/goonstation#427]
[BUG]

**Describe the bug**
Introducing a zombie to a monkey or a pen of monkeys usually resulted in the zombies duplicating via eating the brain of the monkey, much like the player getting turned into an NPC zombie when killed by one. However, all the zombie seems to do is "gnash its teeth in frustration" after attempting to eat the brain of the monkey.

**To Reproduce**
1. Get a zombie. Probably from the debris field.
2. Introduce zombie to monkey and cause them to fight
3. Monkey will not be turned into zombie

**Expected behavior**
The monkey should be turned into a zombie via the zombie eating its brain.

**Screenshots**
https://i.imgur.com/BVp8OVw.png
https://i.imgur.com/JO1T4iI.png

Unsure if I'm remembering this wrong, but I swear people used to create zombie pens and the like by causing zombies to consume several NPC monkeys.

**Comment by Enakai** [comment]
Doesn't actually seem to work on human players, either. Once you reach crit via inflicting damage, the zombies become disinterested and walk off.

https://i.imgur.com/bweNZVM.png

**Comment by flappybatpal** [comment]
At the moment:
Zombies will not target anyone below 0 health.
Zombies will only try to eat anyone under 40% health.
Zombies will attempt to eat brains, this takes 6 seconds and the victim must be laying at the end or the zombie will "gnash its teeth in frustration".

This means if you stand still you are currently safe against zombies because they give up punching and it's associated knockdown attack and just stand there trying to eat your brains. Their chase attack can still hurt you if you move or they are not standing next to you.

I think removing the 40% check and 0% check are fine, this causes them to keep trying to kill you unless you are laying.
I can't test on monkeys because the game eventually crashes:

374 npc.dm ai_target.attack_hand(src) //We're a human!
Exception has occurred: Cannot execute null.attack hand().

**Comment by pali6** [comment]
Note that critters go asleep if there are no living non-npc mobs around, might have caused a part of this issue.
