### ISSUE TITLE
Pronouns follow bodies, not minds

### ISSUE THREAD

**Issue by keiyakins** [goonstation/goonstation#465]
[BUG]

**Describe the bug**
If you end up in someone else's body through, for example, clone shenanigans, your pronouns are set by the body, not the mind.

**To Reproduce**
1. Have pronouns set to something (probably not male because all monkeys seem to use male pronouns)
2. Die.
3. Get monkey cloned

**Expected behavior**
Anything that references your pronouns still uses the set the mind set. ignoring the body.

**Additional context**
Pronouns refer to gender, a mental attribute, not what's between someone's legs.

**Comment by PrimeNumb** [comment]
Changing this would make it much more difficult to impersonate other people, especially for lings.

**Comment by UrsulaMejor** [comment]
I think that this would absolutely be used as a "free" changeling identification method, as we saw with what happened when character flavor text didn't change. Having my pronouns not carry through is kinda a thing, but having my pronouns carry through and then used as a tool to kill me would feel way worse

**Comment by keiyakins** [comment]
Lings could change still, they're changelings, I'm pretty sure to the extent they understand human gender they're inherently genderfluid. But monkey-cloning and the like shouldn't.

**Comment by mybluecorners** [comment]
i think making changes to match your expected behavior would introduce a different point of contention : 
If you play a female character and someone copies your appearance with stable mutagen who is male, now the game is going to be referring to your character as a male and displaying that to people who may not know what gender was the 'intended' one via the character creator. It's kind of a similar thing, but instead of myself being turned into the wrong gender my character is displayed as being the wrong gender when I am not controlling them.

**Comment by ZeWaka** [comment]
To me, this seems like a distinction between OOC and IC pronouns. Imo, pronouns should be tied to your character because this game is played as a character, IC.

**Comment by moonlol** [comment]
What ZeWaka said is what i think is the correct view on this situation. Especially for the rp server. There is a distinction between your character and yourself. Think of it this way, say theres some accident that results in two people having this consciousnesses swapped. These two people are of opposite gender. If you were to examine or talk about their appearance (for example(less likely if you talked to them and they wanted old pronouns but w/e)) you'd use the gender's pronoun to refer to them. For example, "X has some blood on his/her/their shirt" This is the same situation occuring in game. the examine (for example) refers to their physical appearence

**Comment by Adharainspace** [comment]
i agree with some of this stuff but i feel like calling it an ooc issue is kinda lame, idk
like, your characters mind is still your character, right? just like if you scooped my brain out of my body and plopped it into some staffie, i'd still be me, i wouldnt just, magically be this staffie just because my mind was in their body.

**Comment by moonlol** [comment]
well yes but. most things that use pronouns like examine and things like "X snips his/her/their fingers using the wirecutters" are done from an outsiders perspective. if you just met a male and examined them you'd think that they are male no? even if some mind swap shenanigans occurred from the outside it looks like the gender their body is physically

**Comment by JargonRaven** [comment]
Ok, so. Here's my two cents on this, having been trying to make sense of forensics for the last bit now. I'd say, absolutely it's an issue that monkeycloned folks get odd genders, however, stable mutagen, having a specific purpose and intent, to mimic another person, and ling's as well, should copy genders, and leave it up to the players to get grumpy if someone mismatches etc, because that's within realm of impersonation. Another possibility would be making it so that you can adjust gender mid-round, but, fucking who knows how complicated a rework that would be, for what's ultimately flavor-text, so that one I leave to more experienced coders to take up the mantle if that sounds like the best solution. Ideally, monkey cloned people would get the humans genders they were, because monkeys are weird anyway, but I'm unsure of how that could be done within the confines of the code as it is due to that being functionally the same as the case I think should remain impersonation compliant.

**Comment by Connie-Dun** [comment]
I believe that comes down to the disconnect of player perception and character perception. Realistically, you don't know for sure somebody's gender on-sight; of course, people usually make assumptions, typically in a binary fashion. But in the game, people can know on-sight how your character identifies. (The above complications from cloning and similar nonwithstanding).
Given that, mbc's mention - "possible fix another admin suggested was to scrub all gendered pronoun usage from all flavortexts across the whole game. A lot of work but still a possibility if people are fine with that?" - would probably be the ideal solution, in my opinion. Although it would be a lot of work, I am personally willing to put in such an effort. A search of the codebase gives 89 results for "she", 426 for "her",and 311 for "his". Given that the coding tools make it easy to check out each one, and each would be a quick check for context (those searches include, for example, tHIS or tHERe) and replace if appropriate. If anybody's opposed to that, do bring it up, because otherwise it seems like a clear and easy way to handle the issue.

**Comment by UrsulaMejor** [comment]
I'm opposed to it because I rather like being able to present myself as a woman. it brings be a great amount of joy.

**Comment by mordent-goonstation** [comment]
Could we just solve this by having (random, i.e. non Mr. Muggles etc.) monkeys have a random gender?

**Comment by JargonRaven** [comment]
> Could we just solve this by having (random, i.e. non Mr. Muggles etc.) monkeys have a random gender?
That seems like the simplest way for it, or add a button in genetics for modifying it like they get with hair and such. Bit essentialist, but, meh, temporary solution until a better one  ones.

**Comment by mordent-goonstation** [comment]
Worth noting that while doing the "monkeys have random genders" thing is easy, it's not actually that easy to work out what gender a monkey is by looking at them (typically, you have to put e.g. shoes on them to see the "his/her feet" bit on examine). So while this solves the "problem" it's probably not realistically going to be applied (if I'm monkey cloning someone, I'm not going to spend time putting shoes or whatever on monkeys to find one with a matching gender).

We could look to alter the "examine" text to include something that uses his/her or he/she by default (i.e. with nothing equipped). I'm not sure what that would be at this time.

**Comment by mordent-goonstation** [comment]
Could possibly change the `[src.name] seems to be staring blankly into space.` message to be `\he seems to be staring blankly into space.`, which would mean that as NPC monkeys show that message they should indicate that on an examine?
