### ISSUE TITLE
Quick-placing items into boxes and quick-swapping between an item in your inventory and a box in your hand no longer work

### ISSUE THREAD

**Issue by nefarious6th** [goonstation/goonstation#4703]
[BUG]
**Describe the bug**
1. you can no longer immediately drop a box in your active hand by clicking your active hand onto something else (eg, i tried to swap to a knife in my backpack and expected to instantly drop the box and have the knife in my active hand instead)
2. you can no longer hit objects on the ground with a box that has room in it and pick up the objects into the box

**To Reproduce**
1. Have a box
2. Put box in hand
3. Have box on active hand and click to something in backpack (knife)
4. Get message "your hands are full"
5. Try hitting food on ground to place into box when there is space
6. Get message "your hands are full"

**Expected behavior**
Ability to immediately drop the box on the floor and have whatever i clicked on in my inventory in my hand instead for (1). Ability to pick up small items like food into the box by hitting them with the box when there was space still left in the container for (2).

**Comment by Tarmunora** [comment]
re 1: Not even sure if that was intended behaviour in the past - brief testing shows that swapping stuff like that works for things in the same container you're trying to hotswap onto the floor with, and I'm pretty sure I didn't touch that part of small storage code at all. 🤷 
re 2: your offhand now needs to be free in order to put things in storages by clicking on them, because it now actually picks the item up and puts it in the bag instead of just putting it straight from floor into bag, bypassing pickup checks etc

**Comment by nefarious6th** [comment]
No worries; I'm thinking (1) might've had the behavior changed by #4583 versus the cthullu staff checks then? 

What I was doing specifically is that I had a knife in my backpack and a fruit wedge kit box in my hand. I pulled the knife out and put it in my backpack, then grabbed the knife from my equipped backpack using the hand holding the fruit wedge box. I was passively doing this for about 3 hours yesterday when playing and didn't once get the knife to knock the box to the floor like it used to. But I also haven't played enough throughout the past few weeks to know definitively which commit might've changed the behavior.
