### ISSUE TITLE
Locking one ruckingenur kit locks all of them

### ISSUE THREAD

**Issue by penny64** [goonstation/goonstation#4959]
[BUG]

**Describe the bug**
The locks on ruck kits weren't supposed to spread, but currently they do and locking one kit locks every kit- even new ones

**To Reproduce**
1. Lock an item on the ruck kit
2. Check and see that it's locked off station
3. Build a new one
4. See that it's also locked

**Expected behavior**

For kits to not all be bound and locked together

**Comment by Azrun** [comment]
That was the behavior I originally intended. It makes it less of a chore to lock the rkits on maps with distributed rkits (Oshan, Kondaru). Behavior (disseminating item scans) was already distributed so that felt consistent. Also building a new rkit provides all existing database items.

I can see how that behavior wasn't explicit in the description of the PR though.

**Comment by penny64** [comment]
I wouldn't mind actually sitting down and making this consistent- no items in new kits, only packet items are shared, and device scanner items only added locally-

But my thing is that a universal off switch for printing without AA is way too powerful I always assumed that you meant manufacturers and rucks were separate for this

**Comment by Azrun** [comment]
@penny64 Do you feel this issue had been addressed?

**Comment by penny64** [comment]
It be!
