### ISSUE TITLE
Passive gate on Destiny in Hotloop only lets about 25% of the pressure through.

### ISSUE THREAD

**Issue by Zergspower** [goonstation/goonstation#5671]
[BUG] [ENGINE]

**Describe the bug**
Title

**To Reproduce**
1. Start engine
2. Hot loop heats up and pressurizes
3. Passive gate to the left of the engine stays super low resulting in sad engine noises

**Expected behavior**
Follow what the pressure settings are set to 

**Screenshots**
![image](https://user-images.githubusercontent.com/22140677/128276055-ee348b26-965d-471c-a781-5df4ba06937e.png)
As you can see the pressure was set, but still wasn't quite letting it through (sort of visible, pressure was 3300 ish while the main pipes were at 11-12k

**Additional context**
Normal char burn

**Comment by Azrun** [comment]
https://github.com/goonstation/goonstation/blob/7f51873c5dbe6b80d3567f1b8121bc16729a18ce/code/modules/atmospherics/machinery/binary/passive_gate.dm#L47-L54

**Comment by BatElite** [comment]
I'm not sure what bit of that code we're meant to be noticing wrt the issue, it's kinda math-heavy.

**Comment by Azrun** [comment]
Amount of air transferred is based on the target pressure or input vs output (Such that the minimum pressure of target-output or half of input-output). Assuming the output isn't going anywhere after each iteration it'll get half way to input pressure until the delta is 10 kPa(that check is before the posted snippet).

Since this is a dynamic system, where the gas is then going through the TEG, it is not unreasonable that at any given time that the output is half the input. Likely higher of course.

---

The mechanism that limits backflow essentially reduces the rate gas is transferred as it reaches equilibrium with input. It works best when it is trying to achieve a target pressure and not limited by the input pressure.

**Comment by Zergspower** [comment]
That's kind of the reason for the ticket, the intake pressure isn't even half it's more of a quarter of what should be there, making this specific map with this specific passive gate an issue of the engine properly running.  The Output is actually fine, but because of the bottleneck you have to continually bleed the line of pressure with cannisters if you want it to not stall itself out

**Comment by Azrun** [comment]
Which intake are you referring to? 😕

**Comment by Zergspower** [comment]
The Hotloop intake and the connected passivegate, the engine pressure coming in would stay low while the output would stay higher causing that backpressure and power drop problem.
