### ISSUE TITLE
brewing burritos only yields sewage

### ISSUE THREAD

**Issue by Cthucky** [goonstation/goonstation#5682]
[BUG]

**Describe the bug**
Brewing burritos only yields sewage.

**To Reproduce**
1. Buy a burrito.
2. Scan it with the reagent scanner.
3. Brew it in the still.
4. Scan the still with the reagent scanner.

**Expected behavior**
All the fun chems in the burrito appear in the still, plus sewage.

**Comment by ZeWaka** [comment]
weird, can't see any reason why

**Comment by flappybatpal** [comment]
Verified for burritos. Does not occur for the DD noodles.

**Comment by flappybatpal** [comment]
https://github.com/goonstation/goonstation/blob/ff9e23a7c3a529328b800dde0a682644d0967868/code/modules/food_and_drink/discount_dans.dm#L191

Burritos have a brew_result specified which the still will use. It has been like this for the last 16 months.
This is not used on many foods, it is used on snack cakes probably due to some of the reagents. There is uranium in one of the burritos, this may be to prevent reagent farming and duplication?

**Comment by Azrun** [comment]
https://forum.ss13.co/showthread.php?tid=8463&highlight=Brewable++Burritos

**Comment by Azrun** [comment]
6861120c290180e9528610a188b5ebd30a86d567

**Comment by Azrun** [comment]
As designed.
