### ISSUE TITLE
Limbs removed from the body do not match character skin color

### ISSUE THREAD

**Issue by Yellow-Mushroom** [goonstation/goonstation#6032]
[BUG]

**Describe the bug**
Limbs removed from the body do not match character skin color

**To Reproduce**
1. Remove any limb through any means
2. Observe your limbs
3. See as it uses the basic limb sprite, and not representative of your character

**Expected behavior**
Limbs, when removed from the body, should match the skin color of the character

**Comment by BatElite** [comment]
The issue is that limbs get coloured from a mob's `bioHolder.mobAppearance` skintone if possible, but that doesn't get set be

Mobs spawned via roundstart/latejoin will already have the correct appearanceHolder in `AH_we_spawned_with` (for other mobs it'll be null) so it's likely a case of getting `AH_we_spawned_with` into `mobAppearance` before the limbs get created. However my fix half-broke random appearances so uh, best of luck to whoever else is willing to try.

**Comment by ThatFiveGuys** [comment]
Too lazy to find pr but fixed
