### ISSUE TITLE
LOOC text is VERY large, and only yours shows up

### ISSUE THREAD

**Issue by Merlin1230** [goonstation/goonstation#6321]
### Labels

[BUG]

### Description

The LOOC flying text is just MASSIVE, and I can't see anyone but mine!

### Steps to reproduce

1. Say something in LOOC
2. See error.

### Expected Behavior

It to be normal sized

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/76177064/137416368-115e0472-c0c5-44d6-a14c-508160636c9a.png)

**Comment by 112358sam** [comment]
That's strange. That never showed up in my testing. Does it happen every time you use LOOC or are there certain things that trigger it?

**Comment by Zonespace27** [comment]
LOOC size seems different per-person, can confirm that nobody else can see overhead looc, though

**Comment by 112358sam** [comment]
Pali found a potential fix (e070a4c8297d6548a320bb61d56c9569941a3297). It should fix the 'only visible to the speaker' issue. It may have fixed the text size issue as well. If the issue still happens (on rounds starting after this comment is posted) please say so otherwise we should be able to close the issue.

**Comment by 112358sam** [comment]
It's been a few days and I have not seen nor heard any more complaints about either issue since e070a4c8297d6548a320bb61d56c9569941a3297. I think this has been fixed.
