### ISSUE TITLE
Gibber does not produce human meat when people are stuffed in

### ISSUE THREAD

**Issue by vocalpocal** [goonstation/goonstation#6325]
[BUG]
??? this must be some kind of oversight. Was a wrestler chef and two dead guys did not yield a single meat.
Reproduce:
1. Kill human
2. put human in gibber
3. activate gibber
4. ??? where tha meat?

**Comment by Gerhazo** [comment]
Correct, it's a gibber/output_south, pointing at a wall. Even if it pointed correctly to the west, it'd dispense meat in only 2 out of the 3 turfs, since the last one has a disposal outlet on top. The latter of these issues I'll address in my overhaul, but the gibber and its direction itself probably should also be corrected.

**Comment by Gerhazo** [comment]
Donut 3 kitchen now has a correct gibber subtype, per f34cb3e0408fa2dbb9abd8df8734333a890f7a13
The other source of the issue should be resolved with the linked PR.
