### ISSUE TITLE
Sec Segway cannot be crusher'ed 

### ISSUE THREAD

**Issue by Sneedstar** [goonstation/goonstation#6616]
The almighty crusher can not crush a space Segway for some reason. It can crush many things but this is not one of them.

**Comment by MetricDuck** [comment]
Played with on a local - the Segway DOES get crushed, but there's no visible progress bar (unlike with other items) and as the Segway naturally moves out the way due to it being unaffected by either conveyor belts or the pull of the crusher you have to actually park yourself between the grinding wheels for a few moments to get crushed.
