### ISSUE TITLE
Mechianized boots 

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#662]
[BUG]

**Describe the bug**
mech boots dont speed up as they should normally

**To Reproduce**
1. equip boots
2. be sad about your lack of speed

**Expected behavior**
the speed needs to exist

**Comment by triacontakai** [comment]
related to #576 maybe?

**Comment by vuonojenmustaturska** [comment]
Just to reiterate on what i said in discord:
The Actual Fix is: 1) either have the boots adjust their own movespeed property, or 2) have the boots apply a modifier on equip/remove it on unequip
do not add a shoes.speedy check in human movement.

You can perhaps take a look at hermes sandals for inspiration since they seem to be working. 

I can also make a fix PR later, I'm currently working.
