### ISSUE TITLE
Unable to suicide with gas cannister

### ISSUE THREAD

**Issue by Kanthes** [goonstation/goonstation#6673]
### Labels

[BUG]

### Description

Attempting to perform suicide with a gas canister has no effect.

### Steps to reproduce

1. Get a gas cannister (High Pressure Air Cannister for highest pressure at 45MPa)
2. Use the suicide command
3. Select the gas cannister as suicide method.
4. Nothing happens.

### Expected Behavior

I expected to gib.

**Comment by zjdtmkhzt** [comment]
This works as intended, but it's confusing, because you actually need to turn up the release pressure on the tank to at least 5 atmospheres (~510 kPa) .
We should probably put some kind of failure message on this when the pressure is not high enough, or maybe even a scale of effects depending on the release pressure.

**Comment by frawhst** [comment]
clarified in cbf91d5c3b8b348398887231293bffdf6be2704e
