### ISSUE TITLE
Infinite fried meat/biomatter

### ISSUE THREAD

**Issue by Zamazenta** [goonstation/goonstation#6909]
### Labels

[BUG]

### Description

If you put fried meat into an enzymatic reclaimer it will drop a duplicated non-fried meat onto the ground. The fried meat will also be put in the reclaimer which you can eject or reclaim for biomatter. You can re-fry the unfried meat and repeat for infinite meat.

### Steps to reproduce

1. Fry meat
2. Put meat into enzymatic reclaimer
3. Fry the newly created non-fried meat
4. Put new fried meat into enzymatic reclaimer
5. repeat steps 3 and 4

### Expected Behavior

Clicking fried meat on the reclaimer does not duplicate it and somehow un-fry it.

**Comment by TobleroneSwordfish** [comment]
In investigating this I have found that the reclaimer will accept any food item with "meat" or "bacon" in its name, meaning that it will accept empty milk bottles, cabbages, soda bottles and fried anything, as long as they are labelled "meat" with a hand labeller. This probably should be fixed but I'm tempted to leave it just because I love the idea of fooling the reclaimer using labels.
(an easy fix for this would just be to change `name` to `real_name` in the check)
