### ISSUE TITLE
Sometimes you just can't mine a Hardness 0 rock

### ISSUE THREAD

**Issue by Cartlord** [goonstation/goonstation#6976]
### Labels

[BUG]

### Description

Sometimes when mining, you'll encounter a tile - often a rock tile with an anomaly of some kind present - that you just can't mine, even with a pick that  can get through most other rock in one hit.

### Steps to reproduce

1. Pull asteroid
2. Scan
3. Try to mine every rock
4. "You hit the asteroid with the bohrum Mining Pick, but nothing happens!"

### Expected Behavior

It's a rock that the scanner shows as having hardness 0, I should be able to crack it.

### Additional Information & Screenshots

I've found no reliable way to reproduce this, I had it happen most recently at Goon 2 20:03 UTC on December 23rd 2021. Never had it happen from anything other than mineral magnet asteroids, and the rocks usually seem to have anomalies - I've had it happen both on rocks that say they have large objects embedded, and on radioactive rocks. I've never had it happen on a tile that had actual ore.

**Comment by MeggalBozale** [comment]
Might this happen with only particular mining tools? I'm guessing it happened with a matsci pickaxe from the post.

**Comment by zjdtmkhzt** [comment]
I believe this is caused by mining_tools/afterattack() proc not calling the asteroid/event/onHit() proc.
That whole thing should probably be rearranged a bit to make it so that hitting the asteroid also gives the correct message.
(Maybe at some point in the distant future we can even merge generic and matsci mining tools and we'll finally be at peace.)
