### ISSUE TITLE
UI Bug with Taser Shotgun and Power Cell

### ISSUE THREAD

**Issue by FlameArrow57** [goonstation/goonstation#7002]
### Labels

[BUG]

### Description

Tapping a power cell with a taser shotgun while using the TG HUD shows the Goonstation inventory.

### Steps to reproduce

1. Toggle TG HUD before round starts.
2. Spawn as security guard.
3. Buy taser shotgun loadout.
4. Put on security toolbelt.
5. Tap power cell with taser shotgun, with the power cell in the belt.
6. Wait for cell to be swapped out.

### Expected Behavior

The Goonstation inventory should not show up.

### Additional Information & Screenshots

A picture of the result of the bug:

![image](https://user-images.githubusercontent.com/53062374/147402690-f8b30ab5-4e9f-41c6-9113-a4cb8182cb36.png)

**Comment by FlameArrow57** [comment]
Still an issue

**Comment by nefarious6th** [comment]
Related to #7002?

**Comment by FlameArrow57** [comment]
Yea maybe, also #11017

**Comment by MetricDuck** [comment]
It's not just tasers it's cell swap

**Comment by MetricDuck** [comment]
It seems to because the storage hud update() proc is trying to check the users preferences to see if they have tg layout enabled.

Unfortunately, when you click the cell with the tool directly the user is null (I think because the usr is technically the tool...?), so there are no tg preferences set.

See line 116 in storage.dm for the start of this

**Comment by MetricDuck** [comment]
Honestly the best way to solve this would be to implement storage signals via #860
