### ISSUE TITLE
Chomp's key has invaded cog1

### ISSUE THREAD

**Issue by alexeric123** [goonstation/goonstation#7089]
### Labels

[BUG]

### Description

Chomp's key is found in all of chompskis spawn locations.

### Steps to reproduce

1. go around to all the chompski spawn locations given in #6670 
2.  find chomp's key in all of them
3. see error

### Expected Behavior

Finding the actually chompski in one of the spawn locations

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/39737078/148298176-b05ecae6-9517-4acc-aca2-2122cdf05c97.png)

**Comment by Nexusuxen** [comment]
I'm unable to help fix this at the moment since I've already shut off my computer for the night. As a note, one other map uses the spawner I used; Donut 3. However I'm unsure as to how many spawners it has.
When testing I thought it was just a way of letting a player know "hi this is a valid spawn, but you get this useless item instead this time".

**Comment by alexeric123** [comment]
The spawner you are talking about, is the spawner for Chomp's Key, not chompski

**Comment by Nexusuxen** [comment]
oh god damn it- I swear I remember finding Chompski or at least seeing the spawner have use on Donut3 without Chompski himself being in the .dmm
