### ISSUE TITLE
Windoors don't have a north facing sprite

### ISSUE THREAD

**Issue by TobleroneSwordfish** [goonstation/goonstation#7466]
### Labels

[BUG] [SPRITES]

### Description

Windoors' north facing sprite is a copy of the south facing one, leading to jank.

### Steps to reproduce

1. Use reverse engineering fabricator to make a windoor frame
2. Place it facing north
3. Observe that the sprite is just the south facing one and doesn't match the bounding box at all

### Expected Behavior

I expected it to have sprites for all directions

### Additional Information & Screenshots

the path is /obj/machinery/door/airlock/pyro/glass/windoor, found this while fixing another bug with them

**Comment by pali6** [comment]
Ideally would be done via the south sprite shifted north but in order to layer properly that would need the SIDE_MAP map mode, except that currently disables blackness plane which makes some stuff look extremely jank. Byond feature request to change this behaviour has been made but received no reply.
