### ISSUE TITLE
AI-unbolting all doors does not automatically lower them afterwards

### ISSUE THREAD

**Issue by du5tball** [goonstation/goonstation#7585]
### Labels

[BUG]

### Description

AI-unbolting all doors does not automatically lower them afterwards

### Steps to reproduce

1. Bolt open a bunch of doors.
2. Hit the AI "unbolt all doors" button.

### Expected Behavior

Doors should automatically lower again after a set amount of time, like going through them does.

### Additional Information & Screenshots

Unless someone manually closes them, they stay open infinitely since no player interaction takes place and the close-timer doesn't trigger.

**Comment by UrsulaMejor** [comment]
This is a feature request, not a bug. You can also "block doors open" by holding an item in the way of them when they try to auto close, so that they don't close. They will no longer close automatically.

This behavior is expected at this point, and has solidified itself into gameplay.

If we want to change this behavior, I think someone should PR it; it's a remarkably simple bit of code and wouldn't take long for someone to change if we want it.
