### ISSUE TITLE
Editing a list of types in the variable editor is janky

### ISSUE THREAD

**Issue by amylizzle** [goonstation/goonstation#7844]
### Labels

[BUG]

### Description

using the variable editor lists all types in the game

### Steps to reproduce

1. Open variable editor
2. Find a variable to edit
3. It's a list
4. of types
5. PROCESSING PLEASE WAIT
6. Useless list of all types which is not sorted in any useful way.

### Expected Behavior

Probably better to do a text entry that does lookup, like the spawn command

### Additional Information & Screenshots

Please ignore the super secret flock development stuff, but here's a screenshot to illustrate the issue.

![Screenshot from 2022-03-17 11-37-20](https://user-images.githubusercontent.com/3855802/158800643-90a82fd9-2161-4f2a-93b9-cdca6c5e02d9.png)

**Comment by frawhst** [comment]
Yeah there's like 6 different data entry systems (off the top of my head, `list`, `view-variables`, `call-proc`) which all copy paste their own methods
some of them are updated, some... aren't (see 'reference' from 'call-proc', which gives a list of every atom in `world`)
I've been meaning to standardize these, will do sooner rather than later (this weekend at the latest)
