### ISSUE TITLE
north facing MPRT-7 sprite is wrong

### ISSUE THREAD

**Issue by frawhst** [goonstation/goonstation#7894]
### Labels

[trivial]

### Description

The north facing MRPT inhand is the same as the south-facing. This is wrong

### Steps to reproduce

observe via eyeballs

### Expected Behavior

no bug

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/67879783/159148095-bee8ed0d-e9f9-476a-ab8e-f783788afb90.png)

**Comment by Redtrogdor** [comment]
it's mainly a matter of perspective, to me this looks like it's just being pointed at the floor. If it were facing upward instead I think it would look weirder

**Comment by virvatuli-gh** [comment]
fixed [here](https://github.com/goonstation/goonstation/commit/7015877fd1dd685ab65b3f3cfacbe51605a423fb), kind of. Turns out the majority of the RPG's inhands were incorrect, the south facing one was the only one that wasn't flipped or otherwise messed up. I fixed them all and redrew the north facing sprite so it hugs the spaceman a little closer and doesn't hover. Perspective is a little weird still since it's facing downwards but that's more of an issue with the north facing human needing more headroom to properly perspectivize an inhand such as this.
