### ISSUE TITLE
NAS-T believes monkis are human and thus attacks monkis

### ISSUE THREAD

**Issue by atenie** [goonstation/goonstation#8113]
### Labels

[BUG]

### Description

NAS-T believes monkis are human and thus attacks monkis. Doesn't attack humans (??? needs more testing)

### Steps to reproduce

1. Install a NAS-T
2. Stay in front of NAS-T
3. Monki behind you, NAS-T in front of you
4. Watch as you die because of a monki
5. Watch as NAS-T does _not_ attack humans (not entirely sure here, needs more checks. As a mere mortal, I can spawn as nukie so many times.)

### Expected Behavior

Monkis are disregarded completely

**Comment by Merlin1230** [comment]
Honestly, I like the turrets targeting monkeys. It makes the turrets a really fun way to deal with monkey outbreaks after someone buys them all from the vendor. Maybe it can be changed for the NAS-T but players CAN also be monkeys.

**Comment by frawhst** [comment]
Yeah, this isn't STRICTLY intentional, but makes sense as monkeys are just a subtype of human (or, for player monkeys, humans with a gene).
I'm guessing the turret not shooting you was because you were a nuke op; the nukie turrets won't shoot anyone with an agent card (which nuke ops start with).
Works well enough for me.
