### ISSUE TITLE
Floor bots that attempt to remove tiles that originally had prebuild map windows/etc pull up a tile but the plating remains.

### ISSUE THREAD

**Issue by Momoberry** [goonstation/goonstation#8921]
### Labels

[BUG] [MINOR]

### Description

When a floorbot attempts to remove the floor of something that had a prebuilt structure like a window or a wall, it will pull up a tile but the plating will not be removed.

### Steps to reproduce

1. remove a window that is round start.
2. emag floorbot and drag it to that tile
3. watch it remove the tile but the plating remains.

### Expected Behavior

Removes the plating normally.

### Additional Information & Screenshots

This is not guaranteed, some are fine but some are not. it's oddly mixed. This is a part of a bigger issue with the entire space that these areas have, not just the plating/flooring of things that spawn with windows in certain areas.

**Comment by TheTyrant25** [comment]
this is not a bug. Windows are not turfs, they're objects that sit on a turf. They're typically made using wingrille spawners, and the standard operating procedure is to place plating underneath windows, instead of floor tiles. Naturally, some spots are missed. That said, the windows are _meant_ to have plating under them.

Plating behaves oddly with floor tiles and prying, as they're sort of a floor tile of plating that looks exactly identical to the plating underneath when you pry it up. Indicative of a different issue? yes. But not a problem with the floorbot.

This doesn't happen with walls because they are turfs and don't have floor under them until they're destroyed/deconstructed.

**Comment by TheTyrant25** [comment]
Having just double checked, this plating as floor with plating under it also seems to not be a bug anymore
