### ISSUE TITLE
get_xp is slow

### ISSUE THREAD

**Issue by pali6** [goonstation/goonstation#918]
Current XP system sends / receives data on every call. Instead it should archive those and only do that at the end of the round. (It actually kinda archives the data already but doesn't use that.)

**Comment by Kyle2143** [comment]
I told pali in discord, but I thought I'd post in here for posterity.
I've basically got the new system of just making the db call on round end, but I'm heasitant to roll out this new system to live because due to the way byond hub scores which we use for job xp works, we can really only test changes live. Short of registering another game and server and going through that.

As a result, I don't want to attempt it until we can back up the data stored on the byond hub. And unfortunately, the most practical way to do this, using world.GetScores() is currently bugged and not providing the correct output. The only other option is to actually scrape the byond hub website, which luckily someone over at tg did when they ran into the same problem a ywar ago. But that seems like overkill for what is probably a simple bug. So I made a bug report on the byond forums and we'll see about that when it's resolved.
