### ISSUE TITLE
Glass doors are invisible in the bee sanctuary prefab

### ISSUE THREAD

**Issue by DimWhat** [goonstation/goonstation#9236]
### Labels

[BUG]

### Description

All instances of glass door in this prefab are currently invisible yet function fine

### Steps to reproduce

1. Go to the bee sanctuary prefab (the one with zombees and the portagene)
2. Get to the lobby of the prefab.
3. See a distinct lack of doors

### Expected Behavior

To have visible doors (don't we already have perspective ones?)

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/40079883/174522022-62a36692-5a4a-4ce1-b94a-fd6a59ee6e77.png)
![image](https://user-images.githubusercontent.com/40079883/174522071-2eb88b3c-8218-4582-9e48-c39718a518c0.png)

**Comment by ZeWaka** [comment]
to fix: replace doors

**Comment by flappybatpal** [comment]
From https://github.com/goonstation/goonstation/commit/4ca41fabf38c8bc4a1390b6a5c657251e5367942
Due to an ungodly number of doors across types and maps inheriting then changing the icon file without setting a new icon_state.
Resolved with to restore original door sprites https://github.com/goonstation/goonstation/commit/e1d3998c4ba3301878875288242ac44f61b5eb3d
